export const booksData = [
  {
    id: 1,
    title: "The Midnight Library",
    author: "Matt Haig",
    price: 24.99,
    rating: 4.5,
    reviews: 1250,
    image: "https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=400&h=600&fit=crop",
    genre: "Fiction",
    description: "Between life and death there is a library, and within that library, the shelves go on forever.",
    featured: true
  },
  {
    id: 2,
    title: "Atomic Habits",
    author: "James Clear",
    price: 27.99,
    rating: 4.8,
    reviews: 8900,
    image: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&h=600&fit=crop",
    genre: "Self-Help",
    description: "Tiny Changes, Remarkable Results: An Easy & Proven Way to Build Good Habits & Break Bad Ones",
    featured: true
  },
  {
    id: 3,
    title: "The Silent Patient",
    author: "Alex Michaelides",
    price: 22.99,
    rating: 4.7,
    reviews: 4567,
    image: "https://images.unsplash.com/photo-1512820790803-83ca734da794?w=400&h=600&fit=crop",
    genre: "Thriller",
    description: "A psychological thriller about a woman's act of violence against her husband and her subsequent silence.",
    featured: false
  },
  {
    id: 4,
    title: "Where the Crawdads Sing",
    author: "Delia Owens",
    price: 26.99,
    rating: 4.9,
    reviews: 6789,
    image: "https://images.unsplash.com/photo-1481627834876-b7833e8f5570?w=400&h=600&fit=crop",
    genre: "Mystery",
    description: "A heartbreaking coming-of-age story and a surprising murder investigation.",
    featured: true
  },
  {
    id: 5,
    title: "Educated",
    author: "Tara Westover",
    price: 29.99,
    rating: 4.8,
    reviews: 3456,
    image: "https://images.unsplash.com/photo-1516979187457-637abb4f9353?w=400&h=600&fit=crop",
    genre: "Memoir",
    description: "A memoir about a young girl who, kept out of school, leaves her survivalist family and goes on to earn a PhD.",
    featured: false
  },
  {
    id: 6,
    title: "Project Hail Mary",
    author: "Andy Weir",
    price: 28.99,
    rating: 4.9,
    reviews: 5678,
    image: "https://images.unsplash.com/photo-1532012197267-da84d127e765?w=400&h=600&fit=crop",
    genre: "Science Fiction",
    description: "A lone astronaut must save the earth from disaster in this incredible new science-based thriller.",
    featured: true
  },
  {
    id: 7,
    title: "The Four Winds",
    author: "Kristin Hannah",
    price: 25.99,
    rating: 4.6,
    reviews: 2345,
    image: "https://images.unsplash.com/photo-1531901599638-a89bb60971a3?w=400&h=600&fit=crop",
    genre: "Historical Fiction",
    description: "An epic novel of love and heroism and hope, set against the backdrop of one of America's most defining eras.",
    featured: false
  },
  {
    id: 8,
    title: "The Invisible Life of Addie LaRue",
    author: "V.E. Schwab",
    price: 23.99,
    rating: 4.7,
    reviews: 7890,
    image: "https://images.unsplash.com/photo-1513475382585-d06e58bcb0e0?w=400&h=600&fit=crop",
    genre: "Fantasy",
    description: "A life no one will remember. A story you will never forget.",
    featured: true
  },
  {
    id: 9,
    title: "Klara and the Sun",
    author: "Kazuo Ishiguro",
    price: 26.49,
    rating: 4.4,
    reviews: 1234,
    image: "https://images.unsplash.com/photo-1554757380-2fb69b9f6eaa?w=400&h=600&fit=crop",
    genre: "Science Fiction",
    description: "From the bestselling author of Never Let Me Go, a stunning novel about the nature of love and humanity.",
    featured: false
  },
  {
    id: 10,
    title: "The Paris Library",
    author: "Janet Skeslien Charles",
    price: 24.49,
    rating: 4.3,
    reviews: 987,
    image: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&h=600&fit=crop",
    genre: "Historical Fiction",
    description: "Based on the true story of the librarians at the American Library in Paris during WWII.",
    featured: false
  },
  {
    id: 11,
    title: "The Sanatorium",
    author: "Sarah Pearse",
    price: 21.99,
    rating: 4.2,
    reviews: 876,
    image: "https://images.unsplash.com/photo-1543002588-bfa74002ed7e?w=400&h=600&fit=crop",
    genre: "Thriller",
    description: "A chilling debut in which a detective must uncover the dark history of a luxury hotel in the Alps.",
    featured: false
  },
  {
    id: 12,
    title: "The Last Thing He Told Me",
    author: "Laura Dave",
    price: 25.49,
    rating: 4.5,
    reviews: 3456,
    image: "https://images.unsplash.com/photo-1512820790803-83ca734da794?w=400&h=600&fit=crop",
    genre: "Mystery",
    description: "A gripping mystery about a woman who must think like a detective to uncover the truth about her husband.",
    featured: false
  }
];